import "bootstrap";
import { share } from "../components/share";
import { multipleForm } from "../components/multipleForm";
import { vote } from "../components/vote";
import 'mapbox-gl/dist/mapbox-gl.css';
import { initMapbox } from "../plugins/init_mapbox";
import { initAutocomplete } from "../plugins/init_autocomplete";
import { validateForm } from "../components/form-validation";
share();
multipleForm();
vote();
initMapbox();
initAutocomplete();
validateForm();
